# ===============================
# Application
# ===============================
spring.application.name=coding-platform
server.port=8080

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# ===============================
# PostgreSQL (Render)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d9rjm5v40ujc73blg1sg-a.singapore-postgres.render.com:5432/fluxguard_db
spring.datasource.username=fluxguard_db_user
spring.datasource.password=SZlGnNN5aPzwuTnPy6zDfKbHrs0o9T4u
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# ===============================
# IMPORTANT (remove H2)
# ===============================
spring.h2.console.enabled=false